repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix]
        files: \.(md|mdx)$
        exclude: |
          (?x)^(
              \.docusaurus/|
              build/|
              node_modules/|
              \.git/
          )$

  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: npx lint-staged
        language: system
        pass_filenames: false
        always_run: true
